### ISSUE TITLE
Simple `mapStateToProps` conundrum

### ISSUE THREAD

**Issue by nikolakanacki** [keajs/kea#52] opened 2017-10-21 17:07 UTC
Ok, here is the case. And please correct me if I'm trying to achieve this the "wrong way".

I have an `auth` logic which looks something like this:
```js
// logic/auth.js

export default koa({
  // ... actions, path, etc.
  reducers: ({ actions }) => ({
    user: [null, PropTypes.object, {
      [actions.setUser]: (_, user) => user,
    }],
  }),
});
```

Then I want to have a `HOC` which is called `CheckPermissions` and it should, given the `permissionsCheckCallback`, render children only if the provided function returns `true`.

Now, the way I would go about it with vanilla redux is to have the `CheckPermissions` component connected with the store by giving it a `mapStateToProps` function which would:
- take the `user` from the provided `state`
- take the `permissionsCheckCallback` function from `ownProps`
- return `{ hasPermissions: permissionsCheckCallback(user) }`

This way component is never rerendered even if the user changes but the permissions stay the same (optimal).

Now, I've started doing this in `kea` by having the `CheckPermissions` component (pure function really...) export this:
```js
// components/CheckPermissions.jsx

import Auth from '../logic/auth';
import { connect } from 'kea';

export default connect({
  props: [
    Auth, [
      'user',
    ],
  ],
})((props) => (
  props.hasPermissions(props.user)
  ? props.children
  : null
))
```

But, the `mapStateToProps` concept is happening inside the component, not outside so it does not stop the "rerender" cycle: if the user changes - even if the permissions do not - it will trigger the render.

Now, either I'm not reading the docs right / not getting some core concept of `kea` or this is not possible to do the `kea` way? Sure, I can always target the `user` from the global state (no need to even connect `Auth`) but this is why I'm trying to use `kea`, so I don't have to think about the "global" state and bring "logic" as needed (again - this may be wrong on many levels, and `kea` is not intended to be used this way).

**Comment by nikolakanacki** [comment] 2017-10-21 18:18
Update:
I think I found one way to do it - by creating a `hasPermissions` selector inside the `Auth` logic definition. Selectors can have access to props, so it can check for `checkPermissions` function and run it, `selecting` the value down to simple `true` and `false`.

But... Imho, this is far from optimal since it's now bundled with the `logic` and, looking at what it does, it should be a more of a "logic user" implementation then a "logic provider" implementation (it should live on the other end).

**Comment by mariusandra** [comment] 2017-10-21 20:05
Hey @nikolakanacki , an interesting situation you have there :)

First, Kea is not meant to replace Redux at every instance everywhere. Sometimes, for some special components, it can make sense to revert back to Redux's functions. You an access all the selectors of Auth just with something like `user = Auth.selectors.user(state)`.

That said, there is one way you could achieve what you're after. I haven't tested it, so please let me know if it works.

First, whatever prop is in `connect` should trigger a re-render when it changes. As you specifically wish to avoid that for `user`, don't pass it to `connect`, but manually pass the selector via `Auth.selectors` to `selectors` in `kea({})`. Something like this:

```js
import Auth from '../logic/auth';
import { kea } from 'kea';

export default kea({
  selectors: ({ selectors }) => ({
    hasPermissions: [
      () => [(_, props) => props.hasPermissions, Auth.selectors.user],
      (hasPermissions, user) => hasPermissions(user),
      PropTypes.bool
    ]
  })
})((props) => (
  props.hasPermissions
  ? props.children
  : null
))
```

If I'm not mistaken, this should work, have access to the `hasPermissions` function in the props and to the user in `Auth`, without re-rendering when any of them change, but when the final result of the selector changes.

Then again, this is just a fancy abstraction over `mapStateToProps`, so it might be cleaner to just use it directly.

Cheers and let me know if this works :)

**Comment by nikolakanacki** [comment] 2017-10-21 20:27
@mariusandra Thank you for the fast response, I'll give it a spin a bit later, looks interesting :)

Query: wouldn't this create a new slice in the global store? This is what I currently have, just on the other end - as a selector inside the Auth kea logic.

**Comment by nikolakanacki** [comment] 2017-10-21 20:30
update: "just achieve redux connect" === "just achieve **logically scoped** redux connect"

**Comment by mariusandra** [comment] 2017-10-21 20:38
Hey, indeed that would create a new empty slice in the global store. I think that's a bug and should be fixed. More specifically, if you specify a `path`, it should still create the slice, but if you don't, there's no reason to pollute the store.

I'll have a look at this when I can, but probably not today.

**Comment by nikolakanacki** [comment] 2017-10-21 20:47
Oh, so it is not intended to do this? Ok, it makes so much more sense to me now, so `kea` call is not only (primarily) made for introducing reducers? If this is the case I did not "get" it from the docs.

Note: Maybe even a separate property for a "sliceless" `kea` call.

Awesome lib btw, a nice alternative to `dva`.

**Comment by mariusandra** [comment] 2017-10-21 22:01
Hey, so I released `0.26.5`, which doesn't do that anymore. 

The `connect(options)` function is actually just a shorthand for `kea({ connect: options })`. It doesn't add anything to the store, as there's nothing to add. The same is true if you just use `kea({ selectors: ... })` - nothing to add. That's fixed now.

**Comment by nikolakanacki** [comment] 2017-10-21 22:47
Thanks, confirming it works as expected.

**Comment by nikolakanacki** [comment] 2017-10-22 02:04
I'm reopening this since it the fix introduced a bug.

this:
```js
export const LoginGate = kea({
  selectors: () => ({
    isLoginPath: [
      () => [() => history.location.pathname === '/login'],
      isLoginPath => isLoginPath,
      PropTypes.bool,
    ],
  }),
  connect: {
    props: [
      Auth, [
        'isLoggedIn',
      ],
    ],
  },
})(({ isLoginPath, isLoggedIn, children }) => ( /* stateles component */ ));
```

now yields this:
```
selectors.js:21 Uncaught TypeError: Cannot read property 'inline-2' of undefined
    at selectors.js:21
    at Array.reduce (<anonymous>)
    at pathSelector (selectors.js:20)
    at Object.rootSelector [as root] (selectors.js:43)
    at index.js:360
    at Array.forEach (<anonymous>)
    at index.js:359
    at Object.runComponentSelector [as run] (connectAdvanced.js:26)
    at Connect.initSelector (connectAdvanced.js:178)
    at new Connect (connectAdvanced.js:119)
```

**Comment by mariusandra** [comment] 2017-10-22 03:55
Oh... can you check if `0.26.6` solves this regression?

**Comment by nikolakanacki** [comment] 2017-10-22 04:11
No, still the same:
```
selectors.js:21 Uncaught TypeError: Cannot read property 'inline-2' of undefined
    at selectors.js:21
    at Array.reduce (<anonymous>)
    at pathSelector (selectors.js:20)
    at Object.rootSelector [as root] (selectors.js:43)
    at index.js:360
    at Array.forEach (<anonymous>)
    at index.js:359
    at Object.runComponentSelector [as run] (connectAdvanced.js:26)
    at Connect.initSelector (connectAdvanced.js:178)
    at new Connect (connectAdvanced.js:119)
```

**Comment by mariusandra** [comment] 2017-10-22 07:26
Hey, I'm unable to reproduce this. Could you help pinpointing the issue?

I have created a webpackbin here to play with: https://www.webpackbin.com/bins/-Kx1yEgnZLKaJgB_XUTd

**Comment by nikolakanacki** [comment] 2017-10-23 15:18
I'll get to it in the next couple of days, lets keep this open for now. It might be something weird in my implementation since I was experimenting with the lib.

**Comment by mariusandra** [comment] 2017-10-23 15:33
Ok, thanks and let me know :). Also, could you then check if the bug was caused by the changes I did in `0.26.5` and `.6`... or if it already existed earlier, e.g. with `0.26.4` or before.

**Comment by nikolakanacki** [comment] 2017-10-23 15:39
Yeah, just what I was thinking, so we get a clear picture of where the origin is. It was ~3 in the morning so I just rolled back but I think it had to do with something regarding the `connect` feature, as like it was expecting those loose useless parts of the store to be found in the store tree.

I'm currently creating a tiny (batteries included but optional) admin library at the moment featuring `kea` and `antd`, will get to this asap since I'm also looking forward to a fix.

**Closed** 2017-12-20 13:06 UTC
